packaging_format = 2

id = "lxd"
name = "LXD"
description.en = "Offers a user experience similar to virtual machines but using Linux containers instead"
description.fr = "Offre une expérience utilisateur similaire aux machines virtuelles mais en utilisant des conteneurs Linux à la place"

version = "5.17~ynh1"

maintainers = ["kay0u"]

[upstream]
license = "Apache-2.0"
website = "https://linuxcontainers.org/lxd/"
demo = "https://linuxcontainers.org/lxd/try-it/"
admindoc = "https://linuxcontainers.org/lxd/docs/master/index.html"
code = "https://github.com/canonical/lxd"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
        [resources.sources.main]
        armhf.url = "https://go.dev/dl/go1.21.0.linux-armv6l.tar.gz"
        armhf.sha256 = "e377a0004957c8c560a3ff99601bce612330a3d95ba3b0a2ae144165fc87deb1"
        amd64.url = "https://go.dev/dl/go1.21.0.linux-amd64.tar.gz"
        amd64.sha256 = "d0398903a16ba2232b389fb31032ddf57cac34efda306a0eebac34f0965a0742"
        i386.url = "https://go.dev/dl/go1.21.0.linux-386.tar.gz"
        i386.sha256 = "0e6f378d9b072fab0a3d9ff4d5e990d98487d47252dba8160015a61e6bd0bcba"
        arm64.url = "https://go.dev/dl/go1.21.0.linux-arm64.tar.gz"
        arm64.sha256 = "f3d4548edf9b22f26bbd49720350bbfe59d75b7090a1a2bff1afad8214febaf3"

        [resources.sources.lxd]
        url = "https://github.com/canonical/lxd/releases/download/lxd-5.17/lxd-5.17.tar.gz"
        sha256 = "db5a70f10f14623bb175a2b3357a136a7c71c933515d76ee7ab2193c840ae328"

    [resources.system_user]

    [resources.permissions]

    [resources.apt]
    packages = "acl, attr, autoconf, dnsmasq-base, git, libacl1-dev,libcap-dev, liblxc1, lxc-dev, libsqlite3-dev, libtool, libudev-dev, liblz4-dev, libuv1-dev, make, pkg-config, rsync, squashfs-tools, tar, tcl, xz-utils, ebtables, libapparmor-dev, libseccomp-dev, libcap-dev, lvm2, thin-provisioning-tools, btrfs-progs, busybox|busybox-static, libattr1-dev, libuv1, libdevmapper-event1.02.1, dmeventd, lxc, tcl8.6"

