#!/usr/bin/env bash
#
# Sync /etc/dnsmasq.d/lxd and the @lxd_bridges nftables set with the bridges
# managed by LXD.

set -u

dnsmasq_conf="/etc/dnsmasq.d/lxd"

bridges=()
for network in /var/lib/lxd/networks/*; do
    network="${network##*/}"
    [[ -d "/sys/class/net/$network/bridge" ]] && bridges+=("$network")
done

content="$(
    echo "# File generated by lxd-network-sync, do not edit."

    # Not bind-dynamic: dnsmasq refuses to start if another app already set
    # bind-interfaces
    echo "bind-interfaces"

    # Covers the bridges created after this run
    echo "except-interface=lxdbr*"

    for network in "${bridges[@]}"; do
        [[ "$network" == lxdbr* ]] || echo "except-interface=$network"
    done
)"

if [[ "$content" != "$(cat "$dnsmasq_conf" 2> /dev/null)" ]]; then
    echo "$content" > "$dnsmasq_conf"
    chmod 644 "$dnsmasq_conf"
    systemctl restart dnsmasq
fi

if nft list set inet filter lxd_bridges &> /dev/null; then
    nft flush set inet filter lxd_bridges

    if [[ "${#bridges[@]}" -gt 0 ]]; then
        elements="$(printf '"%s", ' "${bridges[@]}")"
        nft add element inet filter lxd_bridges "{ ${elements%, } }"
    fi
fi

exit 0
