#!/bin/bash

#=================================================
# PERSONAL HELPERS
#=================================================

# Create a dedicated systemd socket config
#
# usage: ynh_add_systemd_socket_config [--socket=socket] [--template=template]
# | arg: --socket=      - Socket name (optionnal, `$app` by default)
# | arg: --template=    - Name of template file (optionnal, this is 'systemd' by default, meaning `../conf/systemd.socket` will be used as template)
#
# This will use the template `../conf/<templatename>.socket`.
#
# See the documentation of `ynh_config_add` for a description of the template
# format and how placeholders are replaced with actual variables.
ynh_config_add_systemd_socket() {
    # ============ Argument parsing =============
    local -A args_array=([s]=socket= [t]=template=)
    local socket
    local template
    ynh_handle_getopts_args "$@"
    socket="${socket:-$app}"
    template="${template:-systemd.socket}"
    # ===========================================

    ynh_config_add --template="$template" --destination="/etc/systemd/system/$socket.socket"

    systemctl enable "$socket.socket" --quiet
    systemctl daemon-reload
}


# Remove the dedicated systemd socket config
#
# usage: ynh_config_remove_systemd socket
# | arg: socket   - Socket name (optionnal, $app by default)
ynh_config_remove_systemd_socket() {
    local socket="${1:-$app}"
    if [ -e "/etc/systemd/system/$socket.socket" ]; then
        ynh_systemctl --service="$socket" --action=stop
        systemctl disable "$socket" --quiet
        ynh_safe_rm "/etc/systemd/system/$socket.socket"
        systemctl daemon-reload
    fi
}


# /etc/dnsmasq.d/$app is generated by the sync script, not by a template
_ynh_add_network_sync() {
    ynh_config_add --template="network-sync.sh" --destination="/usr/local/bin/$app-network-sync"
    chmod 755 "/usr/local/bin/$app-network-sync"

    ynh_config_add --template="nftables.conf" --destination="/etc/nftables.d/$app.conf"

    ynh_config_add --template="systemd-sync.service" --destination="/etc/systemd/system/$app-network-sync.service"
    systemctl daemon-reload

    ynh_config_add --template="udev.rules" --destination="/etc/udev/rules.d/99-$app.rules"

    # There is no udev inside a container
    if systemctl is-active --quiet systemd-udevd; then
        udevadm control --reload-rules
    fi

    # Not 'reload': systemd only runs the post_nftables hooks on start
    ynh_systemctl --service=nftables --action=restart

    "/usr/local/bin/$app-network-sync"
}

_ynh_remove_network_sync() {
    if [ -e "/etc/udev/rules.d/99-$app.rules" ]; then
        ynh_safe_rm "/etc/udev/rules.d/99-$app.rules"

        if systemctl is-active --quiet systemd-udevd; then
            udevadm control --reload-rules
        fi
    fi

    if [ -e "/etc/systemd/system/$app-network-sync.service" ]; then
        ynh_safe_rm "/etc/systemd/system/$app-network-sync.service"
        systemctl daemon-reload
    fi

    ynh_safe_rm "/usr/local/bin/$app-network-sync"

    ynh_safe_rm "/etc/nftables.d/$app.conf"
    ynh_systemctl --service=nftables --action=restart

    ynh_safe_rm "/etc/dnsmasq.d/$app"
    ynh_systemctl --service=dnsmasq --action=restart
}

_ynh_add_ld_so() {
    ynh_config_add --template="ld.so.conf" --destination="/etc/ld.so.conf.d/$app.conf"

    ldconfig
}

_ynh_remove_ld_so() {
    ynh_safe_rm "/etc/ld.so.conf.d/$app.conf"

    ldconfig
}

_ynh_set_subuid_subgid() {
    # Remove existing entry first to avoid duplicates on upgrade
    _ynh_unset_subuid_subgid
    echo -e "# Added by lxd\nroot:100000:65536" | tee -a /etc/subuid /etc/subgid
}

_ynh_unset_subuid_subgid() {
    sed -i "/# Added by lxd$/{N;/root:100000:65536/d}" /etc/sub{u,g}id
}
