#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup --src_path="/etc/systemd/system/$app.service"
ynh_backup --src_path="/etc/systemd/system/$app.socket"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup --src_path="/var/log/$app/"

ynh_backup --src_path="/usr/local/lib/$app/"

ynh_backup --src_path="/usr/local/bin/lxc"
ynh_backup --src_path="/usr/local/bin/lxc-to-lxd"
ynh_backup --src_path="/usr/local/bin/lxd"
ynh_backup --src_path="/usr/local/bin/lxd-agent"
ynh_backup --src_path="/usr/local/bin/lxd-benchmark"
ynh_backup --src_path="/usr/local/bin/lxd-metadata"
ynh_backup --src_path="/usr/local/bin/lxd-migrate"
ynh_backup --src_path="/usr/local/bin/lxd-user"

ynh_backup --src_path="/etc/dnsmasq.d/lxd"

ynh_backup --src_path="/etc/ld.so.conf.d/$app.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
