#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/systemd/system/$app.socket"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "/var/log/$app/"

ynh_backup "/usr/local/lib/$app/"

ynh_backup "/usr/local/bin/lxc"
ynh_backup "/usr/local/bin/lxd"
ynh_backup "/usr/local/bin/lxd-agent"
ynh_backup "/usr/local/bin/lxd-benchmark"
ynh_backup "/usr/local/bin/lxd-convert"
ynh_backup "/usr/local/bin/lxd-user"

ynh_backup "/etc/dnsmasq.d/lxd"

ynh_backup "/etc/ld.so.conf.d/$app.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
