#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	ynh_secure_remove --file="$go_tmp"
	ynh_secure_remove --file="$lxd_tmp"
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

app=$YNH_APP_INSTANCE_NAME

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --time --weight=1

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# OPEN A PORT
#=================================================
ynh_script_progression --message="Configuring firewall..." --time --weight=1

ynh_exec_warn_less yunohost firewall allow --no-upnp Both 67

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --time --weight=1

ynh_exec_warn_less ynh_install_app_dependencies $pkg_dependencies

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --time --weight=1

# Download, check integrity, uncompress and patch the source from app.src
go_tmp=$(mktemp -d)
ynh_setup_source --dest_dir="$go_tmp" --source_id="go.$(ynh_detect_arch)"

export PATH=$go_tmp/bin:$PATH

lxd_tmp=$(mktemp -d)
ynh_setup_source --dest_dir="$lxd_tmp" --source_id="lxd"

export GOPATH=${lxd_tmp}/_dist

#=================================================
# BUILD FROM SOURCES
#=================================================
ynh_script_progression --message="Building lxd from sources..." --time --weight=1

pushd ${lxd_tmp}

ynh_exec_warn_less make deps
export CGO_CFLAGS="-I${GOPATH}/deps/raft/include/ -I${GOPATH}/deps/dqlite/include/"
export CGO_LDFLAGS="-L${GOPATH}/deps/raft/.libs -L${GOPATH}/deps/dqlite/.libs/"
export LD_LIBRARY_PATH="${GOPATH}/deps/raft/.libs/:${GOPATH}/deps/dqlite/.libs/"
export CGO_LDFLAGS_ALLOW="-Wl,-wrap,pthread_create"
cd $GOPATH/src/github.com/lxc/lxd

# https://github.com/golang/go/issues/31997#issuecomment-782864390
go env -w GO111MODULE=auto

ynh_exec_warn_less make

mkdir -p /usr/local/lib/$app
mkdir -p /var/log/$app
cp -a ${GOPATH}/deps/{raft,dqlite}/.libs/lib*.so* /usr/local/lib/$app/
cp ${GOPATH}/bin/{lxc,lxd,lxc-to-lxd,lxd-p2c} /usr/local/bin
popd

ynh_secure_remove --file="$go_tmp"
ynh_secure_remove --file="$lxd_tmp"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..." --time --weight=1

# Create a system user
ynh_system_user_create --username=$app

#=================================================
# SPECIFIC SETUP
#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --time --weight=1

# Create a dedicated systemd config
ynh_add_systemd_socket_config
ynh_add_systemd_config

#=================================================
# MODIFY A CONFIG FILE
#=================================================

echo "bind-interfaces
except-interface=lxdbr0" > /etc/dnsmasq.d/lxd
systemctl restart dnsmasq

ynh_store_file_checksum --file="/etc/dnsmasq.d/lxd"

echo "/usr/local/lib/$app/" > /etc/ld.so.conf.d/$app.conf

ynh_store_file_checksum --file="/etc/ld.so.conf.d/$app.conf"

ldconfig

echo "root:1000000:65536 # Added by lxd#" | tee -a /etc/subuid /etc/subgid

#=================================================
# GENERIC FINALIZATION
#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --time --weight=1

yunohost service add $app --log="/var/log/$app/$app.log" --needs_exposed_ports=67

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --time --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --time --last
