#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
install_dir="$(mktemp -d)"
export HOME=${HOME:-"/root/"}
ynh_hide_warnings ynh_go_install
ynh_setup_source  --source_id="main" --dest_dir="$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD FROM SOURCES
#=================================================
ynh_script_progression "Building lxd from sources..."

pushd "$install_dir"
	ynh_hide_warnings make deps
	export CGO_CFLAGS="-I$install_dir/vendor/dqlite/include/"
	export CGO_LDFLAGS="-L$install_dir/vendor/dqlite/.libs/"
	export LD_LIBRARY_PATH="$install_dir/vendor/dqlite/.libs/"
	export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"
	export GOPATH="$install_dir/vendor/"

	ynh_hide_warnings make

	mkdir -p /usr/local/lib/$app
	mkdir -p /var/log/$app
	cp -a $install_dir/vendor/dqlite/.libs/lib*.so* /usr/local/lib/$app/
	cp $install_dir/vendor/bin/{lxc,lxc-to-lxd,lxd,lxd-agent,lxd-benchmark,lxd-metadata,lxd-migrate,lxd-user} /usr/local/bin
popd

ynh_go_remove
ynh_safe_rm "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_add_systemd_socket_config

ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

_ynh_add_dnsmasq

_ynh_add_ld_so

_ynh_set_subuid_subgid

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
