#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=5

# Download, check integrity, uncompress and patch the source from app.src
install_dir="$(mktemp -d)"
export HOME=${HOME:-"/root/"}
ynh_exec_warn_less ynh_install_go --go_version=$GO_VERSION
ynh_setup_source  --source_id="main" --dest_dir="$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD FROM SOURCES
#=================================================
ynh_script_progression --message="Building lxd from sources..." --weight=60

pushd "$install_dir"
	export GOPATH="$install_dir/vendor/"
	ynh_use_go

	ynh_exec_warn_less make deps
	export CGO_CFLAGS="-I$install_dir/vendor/dqlite/include/"
	export CGO_LDFLAGS="-L$install_dir/vendor/dqlite/.libs/"
	export LD_LIBRARY_PATH="$install_dir/vendor/dqlite/.libs/"
	export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

	ynh_exec_warn_less make

	mkdir -p /usr/local/lib/$app
	mkdir -p /var/log/$app
	cp -a $install_dir/vendor/dqlite/.libs/lib*.so* /usr/local/lib/$app/
	cp $install_dir/vendor/bin/{lxc,lxc-to-lxd,lxd,lxd-agent,lxd-benchmark,lxd-metadata,lxd-migrate,lxd-user} /usr/local/bin
popd

ynh_remove_go
ynh_secure_remove --file="$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_socket_config

ynh_add_systemd_config
yunohost service add "$app" --log="/var/log/$app/$app.log"

_ynh_add_dnsmasq

_ynh_add_ld_so

_ynh_set_subuid_subgid

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

# Start a systemd service
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
