#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "/var/log/$app/"

ynh_restore "/usr/local/lib/$app/"

ynh_restore "/usr/local/bin/fuidshift"
ynh_restore "/usr/local/bin/lxc"
ynh_restore "/usr/local/bin/lxc-to-lxd"
ynh_restore "/usr/local/bin/lxd"
ynh_restore "/usr/local/bin/lxd-agent"
ynh_restore "/usr/local/bin/lxd-benchmark"
ynh_restore "/usr/local/bin/lxd-migrate"
ynh_restore "/usr/local/bin/lxd-user"
ynh_restore "/etc/bash_completion.d/lxd-client"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/systemd/system/$app.socket"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_restore "/etc/dnsmasq.d/lxd"
systemctl restart dnsmasq

ynh_restore "/etc/ld.so.conf.d/$app.conf"
ldconfig

_ynh_set_subuid_subgid

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
