#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression --message="Restoring various files..."

ynh_restore_file --origin_path="/var/log/$app/"

ynh_restore_file --origin_path="/usr/local/lib/$app/"

ynh_restore_file --origin_path="/usr/local/bin/lxc"
ynh_restore_file --origin_path="/usr/local/bin/lxc-to-lxd"
ynh_restore_file --origin_path="/usr/local/bin/lxd"
ynh_restore_file --origin_path="/usr/local/bin/lxd-agent"
ynh_restore_file --origin_path="/usr/local/bin/lxd-benchmark"
ynh_restore_file --origin_path="/usr/local/bin/lxd-metadata"
ynh_restore_file --origin_path="/usr/local/bin/lxd-migrate"
ynh_restore_file --origin_path="/usr/local/bin/lxd-user"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..."

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
ynh_restore_file --origin_path="/etc/systemd/system/$app.socket"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_restore_file --origin_path="/etc/dnsmasq.d/lxd"
systemctl restart dnsmasq

ynh_restore_file --origin_path="/etc/ld.so.conf.d/$app.conf"
ldconfig

_ynh_set_subuid_subgid

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
