#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app.socket" --action="stop"
ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Remove old file
if [ -f "/usr/local/bin/lxd-p2c" ]; then
	ynh_safe_rm "/usr/local/bin/lxd-p2c"
fi

sed -i "/root:1000000:65536 # Added by lxd#/d" /etc/sub{u,g}id

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --source_id="go" --dest_dir="$install_dir/go" --full_replace

export PATH="$install_dir/go/bin:$PATH"

ynh_setup_source  --source_id="main" --dest_dir="$install_dir/lxd" --full_replace

export GOPATH="$install_dir/lxd/vendor/"

#=================================================
# BUILD FROM SOURCES
#=================================================
ynh_script_progression "Building lxd from sources..."

pushd "$install_dir/lxd"
	export HOME=${HOME:-"/root/"}

	ynh_hide_warnings make deps
	export CGO_CFLAGS="-I${GOPATH}dqlite/include/"
	export CGO_LDFLAGS="-L${GOPATH}dqlite/.libs/"
	export LD_LIBRARY_PATH="${GOPATH}dqlite/.libs/"
	export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

	ynh_hide_warnings make

	mkdir -p /usr/local/lib/$app
	mkdir -p /var/log/$app
	cp -a ${GOPATH}/dqlite/.libs/lib*.so* /usr/local/lib/$app/
	cp ${GOPATH}/bin/{fuidshift,lxc,lxc-to-lxd,lxd,lxd-agent,lxd-benchmark,lxd-migrate,lxd-user} /usr/local/bin
	cp $install_dir/lxd/scripts/bash/lxd-client /etc/bash_completion.d/
popd

ynh_safe_rm "$install_dir/go"
ynh_safe_rm "$install_dir/lxd"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_add_systemd_socket_config

ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

_ynh_add_dnsmasq

_ynh_add_ld_so

_ynh_set_subuid_subgid

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
